# Generated by Django 6.1.2 on 2026-10-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('avaliacoes', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('pre_requisitos', models.ManyToManyField(blank=True, to='GradePuc.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=100)),
                ('disciplinas_cursadas', models.ManyToManyField(blank=True, to='GradePuc.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='RotinaPreferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios_trabalho', models.CharField(blank=True, max_length=100)),
                ('distribuicao_aulas', models.CharField(blank=True, max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('modalidade', models.CharField(max_length=20)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GradePuc.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_horarios', models.CharField(max_length=100)),
                ('vagas', models.IntegerField()),
                ('sala', models.CharField(max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradePuc.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradePuc.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradePuc.aluno')),
                ('turmas', models.ManyToManyField(to='GradePuc.turma')),
            ],
        ),
    ]
