/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as EletivasRouteImport } from './routes/eletivas'
import { Route as FluxogramaRouteImport } from './routes/fluxograma'
import { Route as GradesSugeridasRouteImport } from './routes/grades-sugeridas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinhaGradeRouteImport } from './routes/minha-grade'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as ResumoRouteImport } from './routes/resumo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const EletivasRoute = EletivasRouteImport.update({
  id: '/eletivas',
  path: '/eletivas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxogramaRoute = FluxogramaRouteImport.update({
  id: '/fluxograma',
  path: '/fluxograma',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesSugeridasRoute = GradesSugeridasRouteImport.update({
  id: '/grades-sugeridas',
  path: '/grades-sugeridas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaGradeRoute = MinhaGradeRouteImport.update({
  id: '/minha-grade',
  path: '/minha-grade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/eletivas': typeof EletivasRoute
  '/fluxograma': typeof FluxogramaRoute
  '/grades-sugeridas': typeof GradesSugeridasRoute
  '/login': typeof LoginRoute
  '/minha-grade': typeof MinhaGradeRoute
  '/questionario': typeof QuestionarioRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/eletivas': typeof EletivasRoute
  '/fluxograma': typeof FluxogramaRoute
  '/grades-sugeridas': typeof GradesSugeridasRoute
  '/login': typeof LoginRoute
  '/minha-grade': typeof MinhaGradeRoute
  '/questionario': typeof QuestionarioRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/eletivas': typeof EletivasRoute
  '/fluxograma': typeof FluxogramaRoute
  '/grades-sugeridas': typeof GradesSugeridasRoute
  '/login': typeof LoginRoute
  '/minha-grade': typeof MinhaGradeRoute
  '/questionario': typeof QuestionarioRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/eletivas'
    | '/fluxograma'
    | '/grades-sugeridas'
    | '/login'
    | '/minha-grade'
    | '/questionario'
    | '/resumo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/eletivas'
    | '/fluxograma'
    | '/grades-sugeridas'
    | '/login'
    | '/minha-grade'
    | '/questionario'
    | '/resumo'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/eletivas'
    | '/fluxograma'
    | '/grades-sugeridas'
    | '/login'
    | '/minha-grade'
    | '/questionario'
    | '/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  EletivasRoute: typeof EletivasRoute
  FluxogramaRoute: typeof FluxogramaRoute
  GradesSugeridasRoute: typeof GradesSugeridasRoute
  LoginRoute: typeof LoginRoute
  MinhaGradeRoute: typeof MinhaGradeRoute
  QuestionarioRoute: typeof QuestionarioRoute
  ResumoRoute: typeof ResumoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletivas': {
      id: '/eletivas'
      path: '/eletivas'
      fullPath: '/eletivas'
      preLoaderRoute: typeof EletivasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxograma': {
      id: '/fluxograma'
      path: '/fluxograma'
      fullPath: '/fluxograma'
      preLoaderRoute: typeof FluxogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades-sugeridas': {
      id: '/grades-sugeridas'
      path: '/grades-sugeridas'
      fullPath: '/grades-sugeridas'
      preLoaderRoute: typeof GradesSugeridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-grade': {
      id: '/minha-grade'
      path: '/minha-grade'
      fullPath: '/minha-grade'
      preLoaderRoute: typeof MinhaGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  EletivasRoute: EletivasRoute,
  FluxogramaRoute: FluxogramaRoute,
  GradesSugeridasRoute: GradesSugeridasRoute,
  LoginRoute: LoginRoute,
  MinhaGradeRoute: MinhaGradeRoute,
  QuestionarioRoute: QuestionarioRoute,
  ResumoRoute: ResumoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
